sonar.host.url=http://localhost:9000
sonar.token=sqa_251b116131382c464863d03be9e966babfbb27ea

sonar.projectKey=appcwds220262
sonar.projectName=Sistema de Denuncias y Sugerencias - Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**, **/*.spec.ts, src/environments/**,src/app/api/**
sonar.coverage.exclusions=**/*

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8