/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiadmincomplaintupdatestatusRequest } from '../../models/apiadmincomplaintupdatestatus-request';

export interface ApiadmincomplaintupdatestatusRequestParams {
      body?: ApiadmincomplaintupdatestatusRequest
}

export function apiadmincomplaintupdatestatus(http: HttpClient, rootUrl: string, params?: ApiadmincomplaintupdatestatusRequestParams, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiadmincomplaintupdatestatus.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiadmincomplaintupdatestatus.PATH = '/admin/complaint/updatestatus';
