/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Apiindexindex$Params as Apiindexindex$Params } from './fn/operations/apiindexindex';
export { apiindexindex as apiindexindex } from './fn/operations/apiindexindex';
