/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Apigeneralindex$Params as Apigeneralindex$Params } from './fn/operations/apigeneralindex';
export { apigeneralindex as apigeneralindex } from './fn/operations/apigeneralindex';
export type { Apisuggestioninsert$Params as Apisuggestioninsert$Params } from './fn/operations/apisuggestioninsert';
export { apisuggestioninsert as apisuggestioninsert } from './fn/operations/apisuggestioninsert';
export type { Apicomplaintinsert$Params as Apicomplaintinsert$Params } from './fn/operations/apicomplaintinsert';
export { apicomplaintinsert as apicomplaintinsert } from './fn/operations/apicomplaintinsert';
export type { Apiofficegetall$Params as Apiofficegetall$Params } from './fn/operations/apiofficegetall';
export { apiofficegetall as apiofficegetall } from './fn/operations/apiofficegetall';
export type { Apisuggestiongetbycode$Params as Apisuggestiongetbycode$Params } from './fn/operations/apisuggestiongetbycode';
export { apisuggestiongetbycode as apisuggestiongetbycode } from './fn/operations/apisuggestiongetbycode';
export type { Apiprofessorgetall$Params as Apiprofessorgetall$Params } from './fn/operations/apiprofessorgetall';
export { apiprofessorgetall as apiprofessorgetall } from './fn/operations/apiprofessorgetall';
