/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Apigeneralindex$Params as Apigeneralindex$Params } from './fn/operations/apigeneralindex';
export { apigeneralindex as apigeneralindex } from './fn/operations/apigeneralindex';
export type { Apisuggestioninsert$Params as Apisuggestioninsert$Params } from './fn/operations/apisuggestioninsert';
export { apisuggestioninsert as apisuggestioninsert } from './fn/operations/apisuggestioninsert';
export type { Apicomplaintinsert$Params as Apicomplaintinsert$Params } from './fn/operations/apicomplaintinsert';
export { apicomplaintinsert as apicomplaintinsert } from './fn/operations/apicomplaintinsert';
export type { Apiofficegetall$Params as Apiofficegetall$Params } from './fn/operations/apiofficegetall';
export { apiofficegetall as apiofficegetall } from './fn/operations/apiofficegetall';
export type { Apisuggestiongetbycode$Params as Apisuggestiongetbycode$Params } from './fn/operations/apisuggestiongetbycode';
export { apisuggestiongetbycode as apisuggestiongetbycode } from './fn/operations/apisuggestiongetbycode';
export type { Apiprofessorgetall$Params as Apiprofessorgetall$Params } from './fn/operations/apiprofessorgetall';
export { apiprofessorgetall as apiprofessorgetall } from './fn/operations/apiprofessorgetall';
export type { Apicomplaintgetbycode$Params as Apicomplaintgetbycode$Params } from './fn/operations/apicomplaintgetbycode';
export { apicomplaintgetbycode as apicomplaintgetbycode } from './fn/operations/apicomplaintgetbycode';
export type { Apicomplaintcommentgetbycode$Params as Apicomplaintcommentgetbycode$Params } from './fn/operations/apicomplaintcommentgetbycode';
export { apicomplaintcommentgetbycode as apicomplaintcommentgetbycode } from './fn/operations/apicomplaintcommentgetbycode';
export type { Apicomplaintcommentinsert$Params as Apicomplaintcommentinsert$Params } from './fn/operations/apicomplaintcommentinsert';
export { apicomplaintcommentinsert as apicomplaintcommentinsert } from './fn/operations/apicomplaintcommentinsert';
export type { ApiuserloginRequestParams as Apiuserlogin$Params } from './fn/operations/apiuserlogin';
export { apiuserlogin as apiuserlogin } from './fn/operations/apiuserlogin';
export type { ApiuserregisterRequestParams as Apiuserregister$Params } from './fn/operations/apiuserregister';
export { apiuserregister as apiuserregister } from './fn/operations/apiuserregister';
export { apiuserauthenticated as apiuserauthenticated } from './fn/operations/apiuserauthenticated';
export type { ApiadmincomplaintgetallRequestParams as Apiadmincomplaintgetall$Params } from './fn/operations/apiadmincomplaintgetall';
export { apiadmincomplaintgetall as apiadmincomplaintgetall } from './fn/operations/apiadmincomplaintgetall';
export type { ApiadminsuggestiongetallRequestParams as Apiadminsuggestiongetall$Params } from './fn/operations/apiadminsuggestiongetall';
export { apiadminsuggestiongetall as apiadminsuggestiongetall } from './fn/operations/apiadminsuggestiongetall';
export type { ApiadmincomplaintupdatestatusRequestParams as Apiadmincomplaintupdatestatus$Params } from './fn/operations/apiadmincomplaintupdatestatus';
export { apiadmincomplaintupdatestatus as apiadmincomplaintupdatestatus } from './fn/operations/apiadmincomplaintupdatestatus';
export type { ApiadminsuggestionupdatestatusRequestParams as Apiadminsuggestionupdatestatus$Params } from './fn/operations/apiadminsuggestionupdatestatus';
export { apiadminsuggestionupdatestatus as apiadminsuggestionupdatestatus } from './fn/operations/apiadminsuggestionupdatestatus';
