/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApicomplaintinsertRequest } from './models/apicomplaintinsert-request';
export type { ApisuggestioninsertRequest } from './models/apisuggestioninsert-request';
