/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApicomplaintinsertRequest {
  complaintFullName?: string;
  description?: string;
  files?: Array<Blob>;
  idOffice?: string;
  idProfessor?: string;
  issueDate?: string;
  personFullName?: string;
}
