/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApisuggestioninsertRequest {
  description?: string;
  files?: Array<Blob>;
  idOffice?: string;
  personFullName?: string;
}
